### ISSUE TITLE
May I ask when the code will be released?

### ISSUE THREAD

**Issue by ClintWestwo0d** [Lemok00/SI-SWE#1]
Brilliant work！
May I ask when the code will be released? Looking forward to the reply!

**Comment by Lemok00** [comment]
Thank you for your interest. Our code is already released in the master branch: https://github.com/Lemok00/SI-SWE/tree/master.

**Comment by ClintWestwo0d** [comment]
> Thank you for your interest. Our code is already released in the master branch: https://github.com/Lemok00/SI-SWE/tree/master.

Thanks a lot ! Appreciated : )
